name: Release
on:
  push:
    tags: ['v*']
permissions:
  contents: read
jobs:
  validate:
    uses: ./.github/workflows/validation.yml
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: ./publish.sh
