name: Validation
on:
  workflow_call:
permissions:
  contents: read
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - run: ./rust.sh
  web:
    runs-on: ubuntu-latest
    steps:
      - run: ./web.sh
